version: '3'

services:
#  fraud-notifier:
#    container_name: fraud-notifier
#    image: kurtis/fraud-notifier:latest
#    depends_on:
#      - messaging
#    ports:
#      - 8080:8082
#    environment:
#      - HTTP_PORT=8082
#      - NATS_ADDRESS=messaging

  messaging:
    container_name: messaging
    image: nats:1.4.1
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  mail:
    container_name: mail
    image: mailhog/mailhog:v1.0.0
    ports:
      - 1025:1025
      - 8025:8025